name: Fetch, Save, and Commit Files

on:  # Triggers
  schedule:
    - cron: '*/10 * * * *'

jobs:
  fetch_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch files and save
        run: |
          curl -O https://geoproxy.in/proxies/HTTP.txt
          curl -O https://geoproxy.in/proxies/SOCKS4.txt
          curl -O https://geoproxy.in/proxies/SOCKS5.txt

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update files"
          git push 
